export const apiRoute = {
  create_product: '/api/admin/product/create/',
  delete_product: '/api/admin/product/delete/',
  detail_product: '/api/admin/product/',
  profile: '/api/user/profile',
  create_voucher: '/api/voucher/create',
  delete_voucher: '/api/voucher/delete',
  create_voucher_code: '/api/voucher/code',
  get_list_order: '/api/orders/book/list',
  create_category: '/api/category/create',
  upload_image: '/api/storage/upload/',
  list_category: '/api/admin/category/',
  list_subcategory: '/api/admin/subcategory/',
  list_sub_subcategory: '/api/admin/sub_subcategory/',
};
